# For configuration options, see 
#   https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file

apiVersion: 1

datasources:
  - name: testdata
    type: testdata
    access: proxy
    uid: testdata_uid
    orgId: 1
    basicAuth: false
    isDefault: true