services:
  smtp:
    image: ixdotai/smtp:v0.5.2
    ports:
      - 127.0.0.1:25:25
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-12.0.2}
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp:25
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=play-demo@grafana.com
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning